# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'aaaa-aaaa-aaaa-aaaa-aaaaa'
  imageRepository: 'ubuntu-qt'
  containerRegistry: 'myregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/docker-qt-build/Dockerfile'
  imageName: 'pabeu/my-repo'  

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  displayName: Build
  inputs:
    command: build
    containerRegistry: my-docker-hub-registry
    repository: '$(imageName)'
    tags: latest
    #arguments: '--build-arg ubuntu_version=18.04 --build-arg qt_version_major=5.12 --build-arg qt_version_full=5.12.4'

- task: Docker@2
  displayName: Push
  inputs:
    command: push
    containerRegistry: my-docker-hub-registry
    repository: '$(imageName)'
    tags: latest
#docker build -t docker-demo .
#docker tag docker-demo pabeu/my-repo:docker-demo
#docker push pabeu/my-repo:docker-demo
#d716b6dd-e5bd-49c5-8cac-2865202787ef
